[package]
name = "wwise-rank"
version = "0.1.0"
description = "Real-time WAAPI activity monitor and gamified score overlay for Wwise audio engineers"
authors = ["xmimu"]
license = "MIT"
edition = "2021"
default-run = "wwise-rank"

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "wwise_rank_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-autostart = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
waapi-rs = "0.2.2"
tokio = { version = "1", features = ["full"] }
sysinfo = "0.33"
